#!/bin/bash

java -cp ".:../artifacts/IterativeParallelismTest.jar:../artifacts/ParallelMapperTest.jar:../lib/hamcrest-core-1.3.jar:../lib/junit-4.11.jar:../lib/quickcheck-0.6.jar:../out/production/java-advanced" info.kgeorgiy.java.advanced.concurrent.Tester list ru.ifmo.ctddev.chekmenev.iterativeparallelism.IterativeParallelism $1
